# Generated by Django 2.1 on 2020-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foomodel',
            name='extra',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
