# Generated by Django 2.1 on 2020-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_foomodel_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='foomodel',
            name='pre_serializer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
